### PR TITLE
Deduplicate yarn dependencies

### PR DESCRIPTION
**Pull request by aluccaroni**
Removing duplicated dependency from yarn.lock to prevent downloading insecure dependency.

### CODE REVIEW

**Comment by eolivelli** [comment]
out of curiosity how did you write this patch ? manually ?

a part from that, did you test the result manually ?
we don't have tests that cover the UI at the moment

**Comment by aluccaroni** [comment]
@eolivelli I've used https://www.npmjs.com/package/yarn-deduplicate. I'll perform some manual checks since we don't have test for the UI (my bad).

Using yarn audit I see before patch:
242 vulnerabilities found - Packages audited: 2024
Severity: 169 Moderate | 73 High
Done in 2.99s.

After:
86 vulnerabilities found - Packages audited: 1699
Severity: 71 Moderate | 15 High
Done in 2.62s.

**Review by eolivelli — APPROVED** [review]
+1

**Comment by eolivelli** [comment]
@aluccaroni feel free to merge as soon as you are happy with your manual testing

thanks

**Pull request merged**
